### NDVI filtering

In [1]:
import pandas as pd
import ast
import numpy as np
import re 
df=pd.read_csv("/home/idisc02/Downloads/atlas_new.csv",encoding='latin-1')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   system:index                      99 non-null     object
 1   Name                              99 non-null     object
 2   tree_cover_area_2000              99 non-null     float64
 3   tree_cover_area_2005              99 non-null     float64
 4   tree_cover_area_2010              99 non-null     float64
 5   tree_cover_area_2015              99 non-null     float64
 6   tree_cover_area_2020              99 non-null     float64
 7   intersecting_roads_count          99 non-null     int64
 8   total_road_length_km              99 non-null     float64
 9   built_area                        99 non-null     float64
 10  NDVI_01                           99 non-null     float64
 11  NDVI_02                           99 non-null     float64
 12  NDVI_03                           99 non-null     float64
 13  NDVI_04                           99 non-null     float64
 14  NDVI_05                           99 non-null     float64
 15  NDVI_06                           99 non-null     float64
 16  NDVI_07                           99 non-null     float64
 17  NDVI_08                           99 non-null     float64
 18  NDVI_09                           99 non-null     float64
 19  NDVI_10                           99 non-null     float64
 20  NDVI_11                           99 non-null     float64
 21  NDVI_12                           99 non-null     float64
 22  cropland_gain_from_trees          99 non-null     float64
 23  cropland_loss_to_tree             99 non-null     float64
 24  permanent_water                   99 non-null     int64
 25  short_vegetation_after_tree_loss  99 non-null     float64
 26  .geo                              98 non-null     object
dtypes: float64(22), int64(2), object(3)
memory usage: 21.0+ KB

In [2]:
df.head()

,system:index,Name,tree_cover_area_2000,tree_cover_area_2005,tree_cover_area_2010,tree_cover_area_2015,tree_cover_area_2020,intersecting_roads_count,total_road_length_km,built_area,...,NDVI_08,NDVI_09,NDVI_10,NDVI_11,NDVI_12,cropland_gain_from_trees,cropland_loss_to_tree,permanent_water,short_vegetation_after_tree_loss,.geo
0,0_00000000000000000000,Polygon108,0.003756,0.003756,0.003756,0.003756,0.003756,0,0.0,0.000000,...,0.356167,0.208837,0.194574,0.181457,0.145718,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-76.4442911..."
1,0_00000000000000000001,Polygon70,0.015608,0.015608,0.015608,0.015608,0.015608,0,0.0,0.000000,...,0.227147,0.280666,0.239797,0.235259,0.187615,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-100.196192..."
2,0_00000000000000000002,Polygon99,0.002013,0.002013,0.002013,0.002013,0.002013,0,0.0,0.000000,...,0.261790,0.173243,0.193281,0.129622,0.155900,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-76.4369961..."
3,0_00000000000000000003,Polygon9,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,23.858824,...,0.161907,0.128487,0.083844,0.179262,0.235469,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-9.12440874..."
4,0_00000000000000000004,Polygon109,0.010531,0.010531,0.010531,0.010531,0.010531,0,0.0,0.000000,...,0.380078,0.221231,0.222260,0.200436,0.072553,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-76.4365279..."

In [3]:


def find_top_three_ndvi_months(row):
    ndvi_columns = ['NDVI_01', 'NDVI_02', 'NDVI_03', 'NDVI_04', 'NDVI_05', 'NDVI_06', 
                    'NDVI_07', 'NDVI_08', 'NDVI_09', 'NDVI_10', 'NDVI_11', 'NDVI_12']
    ndvi_values = []

    # Collecting NDVI values and their corresponding months
    for column in ndvi_columns:
        month_number = column.split('_')[1]
        ndvi_value = row[column]
        ndvi_values.append((ndvi_value, month_number))

    # Sorting the list by NDVI values in descending order
    ndvi_values.sort(reverse=True, key=lambda x: x[0])

    # Extracting the top three months
    top_three_months = [int(month) for _, month in ndvi_values[:3]]

    return top_three_months


df['Top_Three_NDVI_Months'] = df.apply(find_top_three_ndvi_months, axis=1)


ndvi_columns_to_drop = ['NDVI_01', 'NDVI_02', 'NDVI_03', 'NDVI_04', 'NDVI_05', 'NDVI_06', 
                        'NDVI_07', 'NDVI_08', 'NDVI_09', 'NDVI_10', 'NDVI_11', 'NDVI_12']


df.drop(columns=ndvi_columns_to_drop, inplace=True)


df.head()

,system:index,Name,tree_cover_area_2000,tree_cover_area_2005,tree_cover_area_2010,tree_cover_area_2015,tree_cover_area_2020,intersecting_roads_count,total_road_length_km,built_area,cropland_gain_from_trees,cropland_loss_to_tree,permanent_water,short_vegetation_after_tree_loss,.geo,Top_Three_NDVI_Months
0,0_00000000000000000000,Polygon108,0.003756,0.003756,0.003756,0.003756,0.003756,0,0.0,0.000000,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-76.4442911...","[8, 7, 1]"
1,0_00000000000000000001,Polygon70,0.015608,0.015608,0.015608,0.015608,0.015608,0,0.0,0.000000,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-100.196192...","[9, 1, 4]"
2,0_00000000000000000002,Polygon99,0.002013,0.002013,0.002013,0.002013,0.002013,0,0.0,0.000000,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-76.4369961...","[7, 8, 1]"
3,0_00000000000000000003,Polygon9,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,23.858824,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-9.12440874...","[2, 1, 4]"
4,0_00000000000000000004,Polygon109,0.010531,0.010531,0.010531,0.010531,0.010531,0,0.0,0.000000,0.0,0.0,0,0.0,"{""type"":""Polygon"",""coordinates"":[[[-76.4365279...","[8, 7, 10]"

In [4]:
df.to_csv("/home/idisc02/Downloads/atlas_new.csv", index=False)

### LOSS columns Filtering

In [ ]:

df_km=pd.read_csv("/home/idisc02/Forest_Monitoring/input/meta_data_CSV_FILES/With_NDVI/verra_aggregaated.csv")

df_km["loss_groups"]

In [ ]:



def parse_loss_groups(loss_groups):
  
    all_groups = {f"group_{i}": 0 for i in range(24)}  # defining the 24 groups (0 to 23)- representing 2000 to 2023
    
    if not loss_groups or loss_groups == '[]':
        return all_groups
    
    loss_groups = loss_groups.replace('group=', '"group":').replace('sum=', '"sum":')
    parsed_groups = ast.literal_eval(loss_groups)
    
   
    for item in parsed_groups:
        all_groups[f"group_{item['group']}"] = item['sum']
    
    return all_groups


expanded_columns = df_km['loss_groups'].apply(parse_loss_groups)


expanded_df = pd.DataFrame(expanded_columns.tolist())


group_mapping = {
    0: '2000',
    1: '2001',
    2: '2002',
    3: '2003',
    4: '2004',
    5: '2005',
    6: '2006',
    7: '2007',
    8: '2008',
    9: '2009',
    10: '2010',
    11: '2011',
    12: '2012',
    13: '2013',
    14: '2014',
    15: '2015',
    16: '2016',
    17: '2017',
    18: '2018',
    19: '2019',
    20: '2020',
    21: '2021',
    22: '2022',
    23: '2023'
}


expanded_df.rename(columns=lambda x: group_mapping.get(int(x.split('_')[1]), x), inplace=True)


df_km = df_km.join(expanded_df)

In [ ]:

def calculate_loss_pre_5(row):
    planted_year = row['planting_date_reported']
    years = [str(planted_year - i) for i in range(1, 6)]
    losses = [row[year] for year in years if year in df_km.columns]
    return np.nanmean(losses) if losses else np.nan

def calculate_loss_post_3(row):
    planted_year = row['planting_date_reported']
    years = [str(planted_year + i) for i in range(1, 4)]
    losses = [row[year] for year in years if year in df_km.columns]
    return np.nanmean(losses) if losses else np.nan
def calculate_loss_post_5(row):
    planted_year = row['planting_date_reported']
    years = [str(planted_year + i) for i in range(1, 6)]
    losses = [row[year] for year in years if year in df_km.columns]
    return np.nanmean(losses) if losses else np.nan

df_km['loss_pre_5'] = df_km.apply(calculate_loss_pre_5, axis=1)
df_km['loss_post_3'] = df_km.apply(calculate_loss_post_3, axis=1)
df_km['loss_post_5'] = df_km.apply(calculate_loss_post_5, axis=1)



df_km[['planting_date_reported', 'loss_pre_5','loss_post_3']].tail()

In [ ]:


def calculate_loss_pre_5(row):
    try:
        planted_date = pd.to_datetime(row['planting_date_reported'], errors='coerce')
        if pd.isnull(planted_date):
            return np.nan
        planted_year = planted_date.year
        years = [str(planted_year - i) for i in range(1, 6)]
        losses = [row[year] for year in years if year in df_km.columns]
        return np.nanmean(losses) if losses else np.nan
    except Exception as e:
        return np.nan

def calculate_loss_post_3(row):
    try:
        planted_date = pd.to_datetime(row['planting_date_reported'], errors='coerce')
        if pd.isnull(planted_date):
            return np.nan
        planted_year = planted_date.year
        years = [str(planted_year + i) for i in range(1, 4)]
        losses = [row[year] for year in years if year in df_km.columns]
        return np.nanmean(losses) if losses else np.nan
    except Exception as e:
        return np.nan

def calculate_loss_post_5(row):
    try:
        planted_date = pd.to_datetime(row['planting_date_reported'], errors='coerce')
        if pd.isnull(planted_date):
            return np.nan
        planted_year = planted_date.year
        years = [str(planted_year + i) for i in range(1, 6)]
        losses = [row[year] for year in years if year in df_km.columns]
        return np.nanmean(losses) if losses else np.nan
    except Exception as e:
        return np.nan


df_km['loss_pre_5'] = df_km.apply(calculate_loss_pre_5, axis=1)
df_km['loss_post_3'] = df_km.apply(calculate_loss_post_3, axis=1)
df_km['loss_post_5'] = df_km.apply(calculate_loss_post_5, axis=1)

In [ ]:
columns_to_drop = [str(year) for year in range(2000, 2024)] + ['loss_groups']
df_km = df_km.drop(columns=columns_to_drop, errors='ignore')
df_km.tail()

In [ ]:
df_km.to_csv("/home/idisc02/Forest_Monitoring/input/meta_data_CSV_FILES/With_NDVI/verra_aggregaated.csv")